package com.example;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.time.Duration;
import java.net.MalformedURLException;
import java.net.URL;
public class DeleteStudentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleteStudent() {
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1200, 754));
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".fa")));
    }
    vars.put("initialRowCount", js.executeScript("return document.querySelectorAll(\'.fa\').length;"));
    driver.findElement(By.cssSelector(".even .fa")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.cssSelector("strong"), "Student Data Deleted"));
    }
    assertThat(driver.findElement(By.cssSelector("strong")).getText(), is("Student Data Deleted"));
    vars.put("newRowCount", js.executeScript("return document.querySelectorAll(\'.fa\').length;"));
    if ((Boolean) js.executeScript("return (arguments[0] == arguments[1] - 1)", vars.get("newRowCount"),vars.get("initialRowCount"))) {
      System.out.println("\"Row count decreased correctly\"");
    } else {
      System.out.println("\"Row count did NOT decrease!\"");
    }
  }
}
